#!/usr/bin/env bash
set -eo pipefail

PATH="${PATH-}"
PYTHONPATH="${PYTHONPATH-}"
AMENT_PREFIX_PATH="${AMENT_PREFIX_PATH-}"
LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}"
if [ -z "${RMW_IMPLEMENTATION-}" ]; then
  RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
fi
export RMW_IMPLEMENTATION

set -u
shopt -s nullglob

PYTHONPATH_BASE="@pythonPath@"
if [ -n "$PYTHONPATH_BASE" ]; then
  PYTHONPATH="$PYTHONPATH_BASE${PYTHONPATH:+:}${PYTHONPATH}"
fi
export PYTHONPATH

AMENT_PREFIX_PATH="@amentPrefixPath@"
export AMENT_PREFIX_PATH

LIBRARY_PATH_BASE="@workspaceLibraryPath@"
if [ -n "$LIBRARY_PATH_BASE" ]; then
  LD_LIBRARY_PATH="$LIBRARY_PATH_BASE${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}"
fi
export LD_LIBRARY_PATH

set +u
for prefix in @workspaceRuntimePrefixes@; do
  for script in "$prefix"/setup.bash "$prefix"/local_setup.bash \
                "$prefix"/install/setup.bash "$prefix"/install/local_setup.bash \
                "$prefix"/share/*/local_setup.bash "$prefix"/share/*/setup.bash; do
    if [ -f "$script" ]; then
      echo "[INFO] Sourcing $script" >&2
      . "$script"
    fi
  done
done
set -u

echo "[DEBUG] AMENT_PREFIX_PATH=$AMENT_PREFIX_PATH" >&2
echo "[DEBUG] PYTHONPATH=$PYTHONPATH" >&2
echo "[DEBUG] RMW_IMPLEMENTATION=$RMW_IMPLEMENTATION" >&2

# Launch the pre-generated workspace launch file from the built workspace
# This file is generated by polyflow-studio and copied during the Nix build
WORKSPACE_LAUNCH="@rosWorkspace@/share/nodes.launch.py"

if [ ! -f "$WORKSPACE_LAUNCH" ]; then
  echo "[ERROR] Workspace launch file not found: $WORKSPACE_LAUNCH" >&2
  echo "[ERROR] This file should be generated by polyflow-studio and included in the build" >&2
  exit 1
fi

echo "[INFO] Launching workspace from $WORKSPACE_LAUNCH" >&2
exec ros2 launch "$WORKSPACE_LAUNCH"
